---
apiVersion: v1
kind: Namespace
metadata:
  name: knative-sources
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-manager
  namespace: knative-sources
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventing-sources-controller
rules:
- apiGroups:
  - sources.eventing.knative.dev
  resources:
  - githubsources
  - kuberneteseventsources
  verbs: &everything
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
    - sources.eventing.knative.dev
  resources:
    - containersources
    - containersources/status
    - containersources/finalizers
  verbs: *everything
- apiGroups:
  - sources.eventing.knative.dev
  resources:
  - awssqssources/finalizers
  - githubsources/finalizers
  - kuberneteseventsources/finalizers
  verbs: *everything
- apiGroups:
  - sources.eventing.knative.dev
  resources:
  - githubsources/status
  - kuberneteseventsources/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs: *everything
- apiGroups:
  - serving.knative.dev
  resources:
  - services
  verbs: *everything
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs: *everything
- apiGroups:
  - eventing.knative.dev
  resources:
  - eventtypes
  verbs: *everything
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eventing-sources-controller
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: knative-sources
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eventing-sources-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eventing-sources-addressable-resolver 
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: knative-sources
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: addressable-resolver
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    eventing.knative.dev/source: "true"
    knative.dev/crd-install: "true"
  name: githubsources.sources.eventing.knative.dev
spec:
  group: sources.eventing.knative.dev
  names:
    categories:
    - all
    - knative
    - eventing
    - sources
    kind: GitHubSource
    plural: githubsources
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            accessToken:
              properties:
                secretKeyRef:
                  type: object
              type: object
            eventTypes:
              items:
                enum:
                - check_suite
                - commit_comment
                - create
                - delete
                - deployment
                - deployment_status
                - fork
                - gollum
                - installation
                - integration_installation
                - issue_comment
                - issues
                - label
                - member
                - membership
                - milestone
                - organization
                - org_block
                - page_build
                - ping
                - project_card
                - project_column
                - project
                - public
                - pull_request
                - pull_request_review
                - pull_request_review_comment
                - push
                - release
                - repository
                - status
                - team
                - team_add
                - watch
                type: string
              minItems: 1
              type: array
            ownerAndRepository:
              minLength: 1
              type: string
            secretToken:
              properties:
                secretKeyRef:
                  type: object
              type: object
            serviceAccountName:
              type: string
            sink:
              type: object
          required:
          - ownerAndRepository
          - eventTypes
          - accessToken
          - secretToken
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  severity:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                type: object
              type: array
            sinkUri:
              type: string
            webhookIDKey:
              type: string
          type: object
  version: v1alpha1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    eventing.knative.dev/source: "true"
    knative.dev/crd-install: "true"
  name: kuberneteseventsources.sources.eventing.knative.dev
spec:
  group: sources.eventing.knative.dev
  names:
    categories:
    - all
    - knative
    - eventing
    - sources
    kind: KubernetesEventSource
    plural: kuberneteseventsources
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            namespace:
              type: string
            serviceAccountName:
              type: string
            sink:
              type: object
          required:
          - namespace
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  severity:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                type: object
              type: array
            sinkUri:
              type: string
          type: object
  version: v1alpha1
---
apiVersion: v1
kind: Service
metadata:
  name: controller
  namespace: knative-sources
  labels:
    control-plane: controller-manager
spec:
  selector:
    control-plane: controller-manager
  ports:
  - port: 443
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: controller-manager
  namespace: knative-sources
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels: &labels
      control-plane: controller-manager
  serviceName: controller-manager
  template:
    metadata:
      labels: *labels
    spec:
      serviceAccountName: controller-manager
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/knative-eventing/knative-eventing-sources-manager:ci
        name: manager
        env:
        - name: K8S_RA_IMAGE
          value: image-registry.openshift-image-registry.svc:5000/knative-eventing/knative-eventing-sources-kuberneteseventsource:ci
        - name: GH_RA_IMAGE
          value: image-registry.openshift-image-registry.svc:5000/knative-eventing/knative-eventing-sources-github-receive-adapter:ci
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Namespace
metadata:
  name: knative-sources
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: camel-controller-manager
  namespace: knative-sources
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: camel-controller
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - sources.eventing.knative.dev
  resources:
  - camelsources
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - sources.eventing.knative.dev
  resources:
  - camelsources/status
  - camelsources/finalizers
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - camel.apache.org
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: camel-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: camel-controller
subjects:
- kind: ServiceAccount
  name: camel-controller-manager
  namespace: knative-sources
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eventing-sources-camel-controller-addressable-resolver
subjects:
- kind: ServiceAccount
  name: camel-controller-manager
  namespace: knative-sources
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: addressable-resolver
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    eventing.knative.dev/source: "true"
    knative.dev/crd-install: "true"
  name: camelsources.sources.eventing.knative.dev
spec:
  group: sources.eventing.knative.dev
  names:
    categories:
    - all
    - knative
    - eventing
    - sources
    kind: CamelSource
    plural: camelsources
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            image:
              type: string
            serviceAccountName:
              type: string
            sink:
              type: object
            source:
              properties:
                component:
                  properties:
                    properties:
                      type: object
                    uri:
                      minLength: 1
                      type: string
                  type: object
              type: object
          required:
          - source
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  severity:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                type: object
              type: array
            sinkUri:
              type: string
          type: object
  version: v1alpha1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: camel-controller-manager
  name: camel-controller-manager
  namespace: knative-sources
spec:
  selector:
    control-plane: camel-controller-manager
  ports:
  - port: 443
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    control-plane: camel-controller-manager
  name: camel-controller-manager
  namespace: knative-sources
spec:
  selector:
    matchLabels:
      control-plane: camel-controller-manager
  serviceName: camel-controller-manager
  template:
    metadata:
      labels:
        control-plane: camel-controller-manager
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/knative-eventing/knative-eventing-sources-camel-source-controller:ci
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 20m
            memory: 20Mi
      serviceAccount: camel-controller-manager
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-controller-manager
  namespace: knative-sources
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventing-sources-kafka-controller
rules:
- apiGroups:
  - sources.eventing.knative.dev
  resources:
  - kafkasources
  - kafkasources/finalizers
  verbs: &everything
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - sources.eventing.knative.dev
  resources:
  - kafkasources/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs: *everything
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs: *everything
- apiGroups:
  - eventing.knative.dev
  resources:
  - eventtypes
  verbs: *everything
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eventing-sources-kafka-controller
subjects:
- kind: ServiceAccount
  name: kafka-controller-manager
  namespace: knative-sources
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eventing-sources-kafka-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eventing-sources-kafka-controller-addressable-resolver 
subjects:
- kind: ServiceAccount
  name: kafka-controller-manager
  namespace: knative-sources
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: addressable-resolver
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    eventing.knative.dev/source: "true"
    knative.dev/crd-install: "true"
  name: kafkasources.sources.eventing.knative.dev
spec:
  group: sources.eventing.knative.dev
  names:
    categories:
    - all
    - knative
    - eventing
    - sources
    kind: KafkaSource
    plural: kafkasources
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            bootstrapServers:
              type: string
              minLength: 1
            topics:
              type: string
              minLength: 1
            consumerGroup:
              type: string
              minLength: 1
            net:
              properties:
                sasl:
                  properties:
                    enable:
                      type: boolean
                    password:
                      properties:
                        secretKeyRef:
                          type: object
                      type: object
                    user:
                      properties:
                        secretKeyRef:
                          type: object
                      type: object
                  type: object
                tls:
                  properties:
                    enable:
                      type: boolean
                  type: object
              type: object
            serviceAccountName:
              type: string
            sink:
              type: object
          type: object
          required:
              - bootstrapServers
              - topics
              - consumerGroup
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  severity:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                type: object
              type: array
            observedGeneration:
              format: int64
              type: integer
            sinkUri:
              type: string
          type: object
  version: v1alpha1
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-controller
  namespace: knative-sources
  labels:
    control-plane: kafka-controller-manager
spec:
  selector:
    control-plane: kafka-controller-manager
  ports:
  - port: 443
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-controller-manager
  namespace: knative-sources
  labels:
    control-plane: kafka-controller-manager
spec:
  selector:
    matchLabels: &labels
      control-plane: kafka-controller-manager
  serviceName: kafka-controller-manager
  template:
    metadata:
      labels: *labels
    spec:
      serviceAccountName: kafka-controller-manager
      containers:
      - name: manager
        image: image-registry.openshift-image-registry.svc:5000/knative-eventing/knative-eventing-sources-kafka-source-controller:ci
        env:
        - name: KAFKA_RA_IMAGE
          value: image-registry.openshift-image-registry.svc:5000/knative-eventing/knative-eventing-sources-kafka-source-adapter:ci
        volumeMounts:
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 20m
            memory: 20Mi
      serviceAccount: kafka-controller-manager
      terminationGracePeriodSeconds: 10
